DROP TABLE IF EXISTS upa.upa_org_salary_pattern;
DROP TABLE IF EXISTS upa.upa_organization;
CREATE TABLE upa.upa_organization (
  ORG_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  ORG_TYPE VARCHAR(3) NOT NULL,
  ORG_NAME VARCHAR(50) NOT NULL,
  TZ_CODE VARCHAR(3) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  LAST_MODIFIED_DATE DATETIME NOT NULL,
  PRIMARY KEY (ORG_ID) USING BTREE
)
ENGINE=InnoDB DEFAULT CHARSET=utf8;
  
CREATE TABLE upa.upa_org_salary_pattern (
  ORG_SP_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  ORG_ID INT(10) UNSIGNED NOT NULL,
  FIRST_DATE DATE NOT NULL,
  LAST_DATE DATE NOT NULL,
  FREQUENCY_TYPE VARCHAR(3) NOT NULL, 
  TZ_CODE VARCHAR(3) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  LAST_MODIFIED_DATE DATETIME NOT NULL, 
  KEY OIG_SP_ORG_IDX (ORG_SP_ID, ORG_ID),
  PRIMARY KEY (ORG_SP_ID) USING BTREE,
  FOREIGN KEY (ORG_ID) REFERENCES upa.upa_organization(ORG_ID)
  )
  ENGINE=InnoDB DEFAULT CHARSET=utf8;
  
/*
app_user
*/
DROP TABLE IF EXISTS upa.app_user;
CREATE TABLE upa.app_user (
  USER_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT ,
  LOGIN_ID VARCHAR(20) NOT NULL,
  USER_PASSWORD VARCHAR(20) NOT NULL,
  USER_LAST_LOGIN_DATE DATETIME NULL,
  ORG_SP_ID INT(10) UNSIGNED NULL,
  TZ_CODE VARCHAR(3) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  LAST_MODIFIED_DATE DATETIME NOT NULL,
  PRIMARY KEY (USER_ID) USING BTREE,
  FOREIGN KEY (ORG_SP_ID) REFERENCES upa.upa_org_salary_pattern(ORG_SP_ID)
  )
  ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into upa.app_user (USER_ID,  LOGIN_ID,  USER_PASSWORD,  USER_LAST_LOGIN_DATE,  ORG_SP_ID, TZ_CODE,  CREATED_DATE, LAST_MODIFIED_DATE)
values(1,'KIWASAKI', 'welcome1',  sysdate(), null, 'US3', sysdate(),  sysdate());
commit;

select * from upa.app_user;

DROP TABLE IF EXISTS upa.upa_user_salary_type;
CREATE TABLE upa.upa_user_salary_type (
  USER_ID INT(10) UNSIGNED NOT NULL UNIQUE,
  SALARY_AMT DECIMAL(10,2) NOT NULL,
  SALARY_CURRENCY_CODE VARCHAR(3) NOT NULL,
  SALARY_TYPE VARCHAR(3) NOT NULL,
  EXEMPT_IND INT(1) NOT NULL,  
  TZ_CODE VARCHAR(3) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  LAST_MODIFIED_DATE DATETIME NOT NULL, 
  FOREIGN KEY (USER_ID) REFERENCES upa.app_user(USER_ID)
  )
  ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*
upa_hand_scan
*/
DROP TABLE IF EXISTS upa.upa_hand_scan_record;
DROP TABLE IF EXISTS upa.upa_hand_scan;

CREATE TABLE upa.upa_hand_scan (
  HEADER_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT primary key,
  USER_ID INT(10) UNSIGNED NOT NULL UNIQUE,
  TERM_TYPE VARCHAR(3) NOT NULL,
  FIRST_DATE DATE NOT NULL,
  LAST_DATE DATE NOT NULL,
  TOTAL_HOUR INT NULL,
  REMAINING_HOUR INT NULL,
  TZ_CODE VARCHAR(3) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  LAST_MODIFIED_DATE DATETIME NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES upa.app_user(USER_ID))
  ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE upa.upa_hand_scan_record (
  HEADER_ID INT(10) UNSIGNED NOT NULL,
  RECORD_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  SCAN_DATE DATE NOT NULL,
  SCAN_IN_TIME TIME NULL,
  SCAN_OUT_TIME TIME NULL,
  PARTICIPATION_TIME TIME NULL,
  TZ_CODE VARCHAR(3) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  LAST_MODIFIED_DATE DATETIME NOT NULL,
  PRIMARY KEY (RECORD_ID) USING BTREE,
  FOREIGN KEY (HEADER_ID) REFERENCES upa.upa_hand_scan(HEADER_ID))
  ENGINE=InnoDB DEFAULT CHARSET=utf8;
  

/*
ERROR/ALERT MESSAGE CODE
*/
DROP TABLE IF EXISTS upa.upa_alert_message;
CREATE TABLE upa.upa_alert_message (
 MESSAGE_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT primary key,
 MESSAGE_CODE VARCHAR(3) NOT NULL,
 MESSAGE_TYPE VARCHAR(3) NOT NULL,
 LANGUAGE_CODE VARCHAR(2) NOT NULL,
 MESSAGE_VALUE VARCHAR(500) NOT NULL,
 TZ_CODE VARCHAR(3) NOT NULL,
 CREATED_DATE DATETIME NOT NULL,
 LAST_MODIFIED_DATE DATETIME NOT NULL,
 KEY MESSAGE_IDX (MESSAGE_CODE, LANGUAGE_CODE)
 )
ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into upa.upa_alert_message (MESSAGE_ID,  MESSAGE_CODE,  MESSAGE_TYPE,  LANGUAGE_CODE,  MESSAGE_VALUE, TZ_CODE,  CREATED_DATE, LAST_MODIFIED_DATE)
values(1,'DUP', 'ERR',  'EN', 'The entered value is already existed.', 'US3', sysdate(),  sysdate());
commit;