/*
app_user
*/
DROP TABLE IF EXISTS upa.app_user;
CREATE TABLE upa.app_user (
  USER_NO INT(10) UNSIGNED NOT NULL AUTO_INCREMENT primary key,
  USER_ID VARCHAR(20) NOT NULL,
  USER_PASSWORD VARCHAR(20) NOT NULL,
  USER_LAST_LOGIN_DATE DATETIME NULL,
  TZ_CODE VARCHAR(3) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  LAST_MODIFIED_DATE DATETIME NOT NULL)
  ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into upa.app_user (USER_NO,  USER_ID,  USER_PASSWORD,  USER_LAST_LOGIN_DATE,  TZ_CODE,  CREATED_DATE, LAST_MODIFIED_DATE)
values(1,'KIWASAKI', 'welcome1',  sysdate(), 'US3',  sysdate(),  sysdate());
commit;

DROP TABLE IF EXISTS upa.upa_user_salary_type;
DROP TABLE IF EXISTS upa.upa_org_salary_pattern;
DROP TABLE IF EXISTS upa.upa_organization;
CREATE TABLE upa.upa_organization (
  ORG_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT primary key,
  ORG_TYPE VARCHAR(3) NOT NULL,
  ORG_NAME VARCHAR(50) NOT NULL,
  TZ_CODE VARCHAR(3) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  LAST_MODIFIED_DATE DATETIME NOT NULL)
  ENGINE=InnoDB DEFAULT CHARSET=utf8;
  
CREATE TABLE upa.upa_org_salary_pattern (
  ORG_SP_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  ORG_ID INT(10) UNSIGNED NOT NULL,
  FIRST_DATE DATE NOT NULL,
  LAST_DATE DATE NOT NULL,
  FREQUENCY_TYPE VARCHAR(3) NOT NULL, 
  TZ_CODE VARCHAR(3) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  LAST_MODIFIED_DATE DATETIME NOT NULL, 
  KEY OIG_SP_ORG_IDX (ORG_SP_ID, ORG_ID),
  PRIMARY KEY (ORG_SP_ID) USING BTREE,
  FOREIGN KEY (ORG_ID) REFERENCES upa.upa_organization(ORG_ID)
  )
  ENGINE=InnoDB DEFAULT CHARSET=utf8;

  
DROP TABLE IF EXISTS upa.upa_user_salary_type;
CREATE TABLE upa.upa_user_salary_type (
  USER_NO INT(10) UNSIGNED NOT NULL UNIQUE,
  ORG_SP_ID INT(10) UNSIGNED NOT NULL UNIQUE,
  SALARY_AMT DECIMAL(10,2) NOT NULL,
  SALARY_CURRENCY_CODE VARCHAR(3) NOT NULL,
  SALARY_TYPE VARCHAR(3) NOT NULL,
  EXEMPT_IND INT(1) NOT NULL,  
  TZ_CODE VARCHAR(3) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  LAST_MODIFIED_DATE DATETIME NOT NULL, 
  KEY USER_ST_SP_IDX (USER_NO, ORG_SP_ID),
  FOREIGN KEY (USER_NO) REFERENCES upa.app_user(USER_NO),
  FOREIGN KEY (ORG_SP_ID) REFERENCES upa.upa_org_salary_pattern(ORG_SP_ID)
  )
  ENGINE=InnoDB DEFAULT CHARSET=utf8;
 

/*
upa_hand_scan
*/
DROP TABLE IF EXISTS upa.upa_hand_scan_record;
DROP TABLE IF EXISTS upa.upa_hand_scan;

CREATE TABLE upa.upa_hand_scan (
  HEADER_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT primary key,
  TERM_TYPE VARCHAR(3) NOT NULL,
  FIRST_DATE DATE NOT NULL,
  LAST_DATE DATE NOT NULL,
  TOTAL_HOUR INT NULL,
  REMAINING_HOUR INT NULL,
  USER_NO INT(10) UNSIGNED NOT NULL,
  TZ_CODE VARCHAR(3) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  LAST_MODIFIED_DATE DATETIME NOT NULL,
  FOREIGN KEY (USER_NO) REFERENCES upa.app_user(USER_NO))
  ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE upa.upa_hand_scan_record (
  HEADER_ID INT(10) UNSIGNED NOT NULL,
  RECORD_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  SCAN_DATE DATE NOT NULL,
  SCAN_IN_TIME TIME NULL,
  SCAN_OUT_TIME TIME NULL,
  PARTICIPATION_TIME TIME NULL,
  TZ_CODE VARCHAR(3) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  LAST_MODIFIED_DATE DATETIME NOT NULL,
  PRIMARY KEY (RECORD_ID) USING BTREE,
  FOREIGN KEY (HEADER_ID) REFERENCES upa.upa_hand_scan(HEADER_ID))
  ENGINE=InnoDB DEFAULT CHARSET=utf8;
  
  
  